version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: o2gethem_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - o2gethem_network

  redis:
    image: redis:7
    container_name: o2gethem_redis
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - o2gethem_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: o2gethem_backend
    restart: always
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
      - redis
    networks:
      - o2gethem_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: o2gethem_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - o2gethem_network

volumes:
  postgres_data:
  redis_data:

networks:
  o2gethem_network:
    driver: bridge